# -*- coding: utf-8 -*-
import grammar

nouns = {
    u"answer": u"cevap",
    u"animal": u"hayvan",
    u"apartment": u"daire",
    u"apple": u"elma",
    u"baby": u"bebek",
    u"bathroom": u"banyo",
    u"bear": u"ayı",
    u"beer": u"bira",
    u"bicycle": u"bisiklet",
    u"bike": u"bisiklet",
    u"bird": u"kuş",
    u"book": u"kitap",
    u"bowl": u"kase",
    u"boy": u"erkek çocuk",
    u"bread": u"ekmek",
    u"breakfast": u"kahvaltı",
    u"bus": u"otobüs",
    u"cake": u"pasta",
    u"car": u"araba",
    u"cat": u"kedi",
    u"cheese": u"peynir",
    u"chicken": u"tavuk",
    u"child": u"çocuk",
    u"closet": u"dolap",
    u"coffee": u"kahve",
    u"computer": u"bilgisayar",
    u"cow": u"inek",
    u"crab": u"yengeç",
    u"dad": u"baba",
    u"daddy": u"baba",
    u"doctor": u"doktor",
    u"dog": u"köpek",
    u"door": u"kapı",
    u"dress": u"elbise",
    u"duck": u"ördek",
    u"egg": u"yumurta",
    u"elephant": u"fil",
    u"example": u"örnek",
    u"eye": u"göz",
    u"family": u"aile",
    u"father": u"baba",
    u"fish": u"balık",
    u"flower": u"çiçek",
    u"food": u"yemek",
    u"foot": u"ayak",
    u"fork": u"çatal",
    u"friend": u"arkadaş",
    u"frog": u"kurbağa",
    u"fruit": u"meyve",
    u"girl": u"kız",
    u"hand": u"el",
    u"hat": u"şapka",
    u"horse": u"at",
    u"house": u"ev",
    u"husband": u"koca",
    u"jacket": u"ceket",
    u"knife": u"bıçak",
    u"leg": u"bacak",
    u"lemon": u"limon",
    u"lion": u"aslan",
    u"man": u"adam",
    u"meat": u"et",
    u"meeting": u"toplantı",
    u"menu": u"menü",
    u"milk": u"süt",
    u"mom": u"anne",
    u"mommy": u"anne",
    u"mouse": u"fare",
    u"monster": u"canavar",
    u"mother": u"anne",
    u"oil": u"yağ",
    u"orange": u"portakal",
    u"owl": u"baykuş",
    u"ox": u"öküz",
    u"pasta": u"makarna",
    u"person": u"insan",
    u"place": u"yer",
    u"plane": u"uçak",
    u"potato": u"batates",
    u"rabbit": u"tavşan",
    u"road": u"yol",
    u"room": u"oda",
    u"salt": u"tuz",
    u"school": u"okul",
    u"shirt": u"gömlek",
    u"shoe": u"ayakkabı",
    u"skirt": u"etek",
    u"sock": u"çorap",
    u"soup": u"çorba",
    u"spider": u"örümcek",
    u"spoon": u"kaşık",
    u"spouse": u"eş",
    u"story": u"hikâye",
    u"strawberry": u"çilek",
    u"street": u"cadde",
    u"sugar": u"şeker",
    u"table": u"masa",
    u"taxi": u"taksi",
    u"tea": u"çay",
    u"thing": u"şey",
    u"tomato": u"domates",
    u"train": u"tren",
    u"turtle": u"kaplumbağa",
    u"water": u"su",
    u"wife": u"karı",
    u"window": u"pencere",
    u"wine": u"şarap",
    u"woman": u"kadın"
}

irregular_plurals = {
    u"baby": u"babies",
    u"bus": u"buses",
    u"child": u"children",
    u"daddy": u"daddies",
    u"dress": u"dresses",
    u"family": u"families",
    u"fish": u"fishes",
    u"knife": u"knives",
    u"man": u"men",
    u"mommy": u"mommies",
    u"mouse": u"mice",
    u"ox": u"oxen",
    u"person": u"people",
    u"potatoes": u"patates",
    u"story": u"stories",
    u"strawberry": u"strawberries",
    u"tomato": u"tomatoes",
    u"wife": u"wives",
    u"woman": u"women"
}

inverted_irregular_plurals = {value: key for key, value in irregular_plurals.items()}

mutations = {
    u"ayak": u"ayağ",
    u"bacak": u"bacağ",
    u"bebek": u"bebeğ",
    u"cevap": u"cevab",
    u"çocuk": u"çocuğ",
    u"çorap": u"çorab",
    u"dolap": u"dolab",
    u"ekmek": u"ekmeğ",
    u"erkek çocuk": u"erkek çocuğ",
    u"etek": u"eteğ",
    u"gömlek": u"gömleğ",
    u"inek": u"ineğ",
    u"kitap": u"kitab",
    u"köpek": u"köpeğ",
    u"ördek": u"ördeğ",
    u"örnek": u"örneğ",
    u"örümcek": u"örümceğ",
    u"şarap": u"şarab",
    u"su": u"suy",
    u"uçak": u"uçağ",
    u"yemek": u"yemeğ",
    u"yengeç": u"yengec"
}

verbs = {
    u"ask": u"sor",
    u"break": u"kır",
    u"buy": u"al",
    u"cancel": u"iptal et",
    u"close": u"kapat",
    u"come": u"gel",
    u"cry": u"ağla",
    u"die": u"öl",
    u"do": u"yap",
    u"draw": u"çiz",
    u"drink": u"iç",
    u"eat": u"ye",
    u"explain": u"açıkla",
    u"find": u"bul",
    u"finish": u"bitir",
    u"fix": u"düzelt",
    u"forget": u"unut",
    u"go": u"git",
    u"kill": u"öldür",
    u"know": u"bil",
    u"laugh": u"gül",
    u"learn": u"öğren",
    u"like": u"beğen",
    u"love": u"sev",
    u"open": u"aç",
    u"play": u"oyna",
    u"read": u"oku",
    u"remember": u"hatırla",
    u"rest": u"dinlen",
    u"run": u"koş",
    u"say": u"de",
    u"see": u"gör",
    u"sleep": u"uyu",
    u"start": u"başla",
    u"stay": u"kal",
    u"study": u"ders çalış",
    u"take": u"al",
    u"talk": u"konuş",
    u"teach": u"öğret",
    u"tell": u"de",
    u"use": u"kullan",
    u"wait": u"bekle",
    u"walk": u"yürü",
    u"want": u"iste",
    u"wash": u"yıka",
    u"watch": u"izle",
    u"wear": u"giy",
    u"work": u"çalış"
}

irregular_verbs = {
    u"break": u"broke",
    u"buy": u"bought",
    u"close": u"closed",
    u"come": u"came",
    u"cry": u"cried",
    u"die": u"died",
    u"do": u"did",
    u"draw": u"drew",
    u"drink": u"drank",
    u"eat": u"ate",
    u"find": u"found",
    u"forget": u"forgot",
    u"go": u"went",
    u"know": u"knew",
    u"like": u"liked",
    u"love": u"loved",
    u"run": u"ran",
    u"say": u"said",
    u"see": u"saw",
    u"sleep": u"slept",
    u"study": u"studied",
    u"take": u"took",
    u"teach": u"taught",
    u"tell": u"told",
    u"use": u"used",
    u"wear": u"wore"
}

inverted_irregular_verbs = {value: key for key, value in irregular_verbs.items()}

pronouns = {
    u"he": u"o",
    u"ı": u"ben",
    u"i": u"ben",
    u"it": u"o",
    u"she": u"o",
    u"they": u"onlar",
    u"y'all": u"siz",
    u"yall": u"siz",
    u"you": u"sen",
    u"we": u"biz",
}

objpronouns = {
    u"her": u"onu",
    u"him": u"onu",
    u"it": u"onu",
    u"me": u"beni",
    u"them": u"onları",
    u"us": u"bizi",
    u"y'all": u"sizi",
    u"yall": u"sizi",
    u"you": u"seni"
}

determiners = {
    u"a": u"bir",
    u"an": u"bir",
    u"her": u"onun",
    u"his": u"onun",
    u"its": u"onun",
    u"our": u"bizim",
    u"my": u"benim",
    u"that": u"şu",
    u"the": u"",
    u"their": u"onların",
    u"these": u"bu",
    u"this": u"bu",
    u"those": u"şu",
    u"y'all's": u"sizin",
    u"y'alls": u"sizin",
    u"yall's": u"sizin",
    u"yalls": u"sizin",
    u"your": u"senin"
}

numbers = {
    u"zero": u"sıfır",
    u"one": u"bir",
    u"two": u"iki",
    u"three": u"üç",
    u"four": u"dört",
    u"five": u"beş",
    u"six": u"altı",
    u"seven": u"yedi",
    u"eight": u"sekiz",
    u"nine": u"dokuz",
    u"ten": u"on",
    u"eleven": u"on bir",
    u"twelve": u"on iki",
    u"thirteen": u"on üç",
    u"fourteen": u"on dört",
    u"fifteen": u"on beş",
    u"sixteen": u"on altı",
    u"seventeen": u"on yedi",
    u"eighteen": u"on sekiz",
    u"nineteen": u"on dokuz",
    u"twenty": u"yirmi",
    u"twenty-one": u"yirmi bir",
    u"twenty-two": u"yirmi iki",
    u"twenty-three": u"yirmi üç",
    u"twenty-four": u"yirmi dört",
    u"twenty-five": u"yirmi beş",
    u"twenty-six": u"yirmi altı",
    u"twenty-seven": u"yirmi yedi",
    u"twenty-eight": u"yirmi sekiz",
    u"twenty-nine": u"yirmi dokuz",
    u"thirty": u"otuz",
    u"thirty-one": u"otuz bir",
    u"thirty-two": u"otuz iki",
    u"thirty-three": u"otuz üç",
    u"thirty-four": u"otuz dört",
    u"thirty-five": u"otuz beş",
    u"thirty-six": u"otuz altı",
    u"thirty-seven": u"otuz yedi",
    u"thirty-eight": u"otuz sekiz",
    u"thirty-nine": u"otuz dokuz",
    u"forty": u"kırk",
    u"forty-one": u"kırk bir",
    u"forty-two": u"kırk iki",
    u"forty-three": u"kırk üç",
    u"forty-four": u"kırk dört",
    u"forty-five": u"kırk beş",
    u"forty-six": u"kırk altı",
    u"forty-seven": u"kırk yedi",
    u"forty-eight": u"kırk sekiz",
    u"forty-nine": u"kırk dokuz",
    u"fifty": u"elli",
    u"fifty-one": u"elli bir",
    u"fifty-two": u"elli iki",
    u"fifty-three": u"elli üç",
    u"fifty-four": u"elli dört",
    u"fifty-five": u"elli beş",
    u"fifty-six": u"elli altı",
    u"fifty-seven": u"elli yedi",
    u"fifty-eight": u"elli sekiz",
    u"fifty-nine": u"elli dokuz",
    u"sixty": u"altmış",
    u"sixty-one": u"altmış bir",
    u"sixty-two": u"altmış iki",
    u"sixty-three": u"altmış üç",
    u"sixty-four": u"altmış dört",
    u"sixty-five": u"altmış beş",
    u"sixty-six": u"altmış altı",
    u"sixty-seven": u"altmış yedi",
    u"sixty-eight": u"altmış sekiz",
    u"sixty-nine": u"altmış dokuz",
    u"seventy": u"yetmiş",
    u"seventy-one": u"yetmiş bir",
    u"seventy-two": u"yetmiş iki",
    u"seventy-three": u"yetmiş üç",
    u"seventy-four": u"yetmiş dört",
    u"seventy-five": u"yetmiş beş",
    u"seventy-six": u"yetmiş altı",
    u"seventy-seven": u"yetmiş yedi",
    u"seventy-eight": u"yetmiş sekiz",
    u"seventy-nine": u"yetmiş dokuz",
    u"eighty": u"seksen",
    u"eighty-one": u"seksen bir",
    u"eighty-two": u"seksen iki",
    u"eighty-three": u"seksen üç",
    u"eighty-four": u"seksen dört",
    u"eighty-five": u"seksen beş",
    u"eighty-six": u"seksen altı",
    u"eighty-seven": u"seksen yedi",
    u"eighty-eight": u"seksen sekiz",
    u"eighty-nine": u"seksen dokuz",
    u"ninety": u"doksan",
    u"ninety-one": u"doksan bir",
    u"ninety-two": u"doksan iki",
    u"ninety-three": u"doksan üç",
    u"ninety-four": u"doksan dört",
    u"ninety-five": u"doksan beş",
    u"ninety-six": u"doksan altı",
    u"ninety-seven": u"doksan yedi",
    u"ninety-eight": u"doksan sekiz",
    u"ninety-nine": u"doksan dokuz"
}

ns = list(numbers)

def num_under1000(n):
    if n < 100:
        return numbers.get(ns[n])
    else:
        ones = u" " + numbers.get(ns[n%100])
        if ones == u" sıfır":
            ones = u""

        hundreds = numbers.get(ns[int(n/100)]) + u" "
        if hundreds == u"bir ":
            hundreds = u""
        
        return hundreds + u"yüz" + ones

def num(n):
    if n < 1000:
        return num_under1000(n)
    elif n < 1000000:
        ones = u" " + num_under1000(n%1000)
        if ones == u" sıfır":
            ones = u""

        thousands = num_under1000(int(n/1000)) + u" "
        if thousands == u"bir ":
            thousands = u""
        
        return thousands + u"bin" + ones
    else:
        return u"bir hayli"

possessors = [u"her", u"his", u"its", u"our", u"my", u"their", u"y'all's", u"your"]