import enum

class Country(enum.Enum):
    Albania = 0
    Andorra = 1
    Armenia = 2
    Australia = 3
    Austria = 4
    Azerbaijan = 5
    Belarus = 6
    Belgium = 7
    Bosnia_and_Herzegovina = 8
    Bulgaria = 9
    Croatia = 10
    Cyprus = 11
    Czech_Republic = 12
    Denmark = 13
    Estonia = 14
    Finland = 15
    France = 16
    Georgia = 17
    Germany = 18
    Greece = 19
    Hungary = 20
    Iceland = 21
    Ireland = 22
    Israel = 23
    Italy = 24
    Latvia = 25
    Lithuania = 26
    Luxembourg = 27
    Malta = 28
    Moldova = 29
    Monaco = 30
    Montenegro = 31
    Morocco = 32
    Netherlands = 33
    North_Macedonia = 34
    Norway = 35
    Poland = 36
    Portugal = 37
    Romania = 38
    Russia = 39
    San_Marino = 40
    Serbia = 41
    Serbia_and_Montenegro = 42
    Slovakia = 43
    Slovenia = 44
    Spain = 45
    Sweden = 46
    Switzerland = 47
    Turkey = 48
    Ukraine = 49
    United_Kingdom = 50
    Yugoslavia = 51

    def record(self, start, end):
        i = start - 1956
        out = []
        while i <= end - 1956:
            for element in esc[i]:
                if element[0] == self:
                    out.append([element[1], len(esc[i]), i + 1956])
                    break
            i += 1
        return out
    
    def normalized(self, start, end, outof):
        r = self.record(start, end)
        out = []
        for element in r:
            out.append(1 + (outof-1.0)*(element[0]-1)/(element[1]-1))
        return out
    
esc1956 = [[Country.Switzerland, 1],
           [Country.Belgium, 2],
           [Country.France, 2],
           [Country.Germany, 2],
           [Country.Italy, 2],
           [Country.Luxembourg, 2],
           [Country.Netherlands, 2]]

esc1957 = [[Country.Netherlands, 1],
           [Country.France, 2],
           [Country.Denmark, 3],
           [Country.Luxembourg, 4],
           [Country.Germany, 4],
           [Country.Italy, 6],
           [Country.United_Kingdom, 7],
           [Country.Belgium, 8],
           [Country.Switzerland, 8],
           [Country.Austria, 10]]

esc1958 = [[Country.France, 1],
           [Country.Switzerland, 2],
           [Country.Italy, 3],
           [Country.Sweden, 4],
           [Country.Belgium, 5],
           [Country.Austria, 5],
           [Country.Germany, 7],
           [Country.Denmark, 8],
           [Country.Netherlands, 9],
           [Country.Luxembourg, 9]]

esc1959 = [[Country.Netherlands, 1],
           [Country.United_Kingdom, 2],
           [Country.France, 3],
           [Country.Switzerland, 4],
           [Country.Denmark, 5],
           [Country.Italy, 6],
           [Country.Belgium, 6],
           [Country.Germany, 8],
           [Country.Sweden, 9],
           [Country.Austria, 9],
           [Country.Monaco, 11]]

esc1960 = [[Country.France, 1],
           [Country.United_Kingdom, 2],
           [Country.Monaco, 3],
           [Country.Norway, 4],
           [Country.Germany, 4],
           [Country.Belgium, 6],
           [Country.Austria, 7],
           [Country.Switzerland, 8],
           [Country.Italy, 8],
           [Country.Sweden, 10],
           [Country.Denmark, 10],
           [Country.Netherlands, 12],
           [Country.Luxembourg, 13]]

esc1961 = [[Country.Luxembourg, 1],
           [Country.United_Kingdom, 2],
           [Country.Switzerland, 3],
           [Country.France, 4],
           [Country.Denmark, 5],
           [Country.Italy, 5],
           [Country.Norway, 7],
           [Country.Yugoslavia, 8],
           [Country.Spain, 9],
           [Country.Monaco, 10],
           [Country.Finland, 10],
           [Country.Netherlands, 10],
           [Country.Germany, 13],
           [Country.Sweden, 14],
           [Country.Austria, 15],
           [Country.Belgium, 15]]

esc1962 = [[Country.France, 1],
           [Country.Monaco, 2],
           [Country.Luxembourg, 3],
           [Country.Yugoslavia, 4],
           [Country.United_Kingdom, 4],
           [Country.Germany, 6],
           [Country.Finland, 7],
           [Country.Sweden, 7],
           [Country.Italy, 9],
           [Country.Denmark, 10],
           [Country.Norway, 10],
           [Country.Switzerland, 10],
           [Country.Belgium, 13],
           [Country.Spain, 13],
           [Country.Austria, 13],
           [Country.Netherlands, 13]]

esc1963 = [[Country.Denmark, 1],
           [Country.Switzerland, 2],
           [Country.Italy, 3],
           [Country.United_Kingdom, 4],
           [Country.France, 5],
           [Country.Monaco, 5],
           [Country.Austria, 7],
           [Country.Luxembourg, 8],
           [Country.Germany, 9],
           [Country.Belgium, 10],
           [Country.Yugoslavia, 11],
           [Country.Spain, 12],
           [Country.Netherlands, 13],
           [Country.Norway, 13],
           [Country.Finland, 13],
           [Country.Sweden, 13]]

esc1964 = [[Country.Italy, 1],
           [Country.United_Kingdom, 2],
           [Country.Monaco, 3],
           [Country.Luxembourg, 4],
           [Country.France, 4],
           [Country.Austria, 6],
           [Country.Finland, 7],
           [Country.Norway, 8],
           [Country.Denmark, 9],
           [Country.Netherlands, 10],
           [Country.Belgium, 10],
           [Country.Spain, 12],
           [Country.Germany, 13],
           [Country.Portugal, 13],
           [Country.Yugoslavia, 13],
           [Country.Switzerland, 13]]

esc1965 = [[Country.Luxembourg, 1],
           [Country.United_Kingdom, 2],
           [Country.France, 3],
           [Country.Austria, 4],
           [Country.Italy, 5],
           [Country.Ireland, 6],
           [Country.Denmark, 7],
           [Country.Switzerland, 8],
           [Country.Monaco, 9],
           [Country.Sweden, 10],
           [Country.Netherlands, 11],
           [Country.Yugoslavia, 12],
           [Country.Norway, 13],
           [Country.Portugal, 13],
           [Country.Spain, 15],
           [Country.Germany, 15],
           [Country.Belgium, 15],
           [Country.Finland, 15]]

esc1966 = [[Country.Austria, 1],
           [Country.Sweden, 2],
           [Country.Norway, 3],
           [Country.Belgium, 4],
           [Country.Ireland, 4],
           [Country.Switzerland, 6],
           [Country.Yugoslavia, 7],
           [Country.Spain, 7],
           [Country.United_Kingdom, 9],
           [Country.Germany, 10],
           [Country.Luxembourg, 10],
           [Country.Finland, 10],
           [Country.Portugal, 13],
           [Country.Denmark, 14],
           [Country.Netherlands, 15],
           [Country.France, 16],
           [Country.Monaco, 17],
           [Country.Italy, 17]]

esc1967 = [[Country.United_Kingdom, 1],
           [Country.Ireland, 2],
           [Country.France, 3],
           [Country.Luxembourg, 4],
           [Country.Monaco, 5],
           [Country.Spain, 6],
           [Country.Belgium, 7],
           [Country.Sweden, 8],
           [Country.Germany, 8],
           [Country.Yugoslavia, 8],
           [Country.Italy, 11],
           [Country.Portugal, 12],
           [Country.Finland, 12],
           [Country.Netherlands, 14],
           [Country.Austria, 14],
           [Country.Norway, 14],
           [Country.Switzerland, 17]]

esc1968 = [[Country.Spain, 1],
           [Country.United_Kingdom, 2],
           [Country.France, 3],
           [Country.Ireland, 4],
           [Country.Sweden, 5],
           [Country.Germany, 6],
           [Country.Belgium, 7],
           [Country.Monaco, 7],
           [Country.Yugoslavia, 7],
           [Country.Italy, 10],
           [Country.Portugal, 11],
           [Country.Luxembourg, 11],
           [Country.Austria, 13],
           [Country.Switzerland, 13],
           [Country.Norway, 13],
           [Country.Netherlands, 16],
           [Country.Finland, 16]]

esc1969 = [[Country.Spain, 1],
           [Country.United_Kingdom, 1],
           [Country.Netherlands, 1],
           [Country.France, 1],
           [Country.Switzerland, 5],
           [Country.Monaco, 6],
           [Country.Ireland, 7],
           [Country.Belgium, 7],
           [Country.Sweden, 9],
           [Country.Germany, 9],
           [Country.Luxembourg, 11],
           [Country.Finland, 12],
           [Country.Yugoslavia, 13],
           [Country.Italy, 13],
           [Country.Portugal, 15],
           [Country.Norway, 16]]

esc1970 = [[Country.Ireland, 1],
           [Country.United_Kingdom, 2],
           [Country.Germany, 3],
           [Country.Switzerland, 4],
           [Country.France, 4],
           [Country.Spain, 4],
           [Country.Netherlands, 7],
           [Country.Italy, 8],
           [Country.Belgium, 8],
           [Country.Monaco, 8],
           [Country.Yugoslavia, 11],
           [Country.Luxembourg, 12]]

esc1971 = [[Country.Monaco, 1],
           [Country.Spain, 2],
           [Country.Germany, 3],
           [Country.United_Kingdom, 4],
           [Country.Italy, 5],
           [Country.Sweden, 6],
           [Country.Netherlands, 6],
           [Country.Finland, 8],
           [Country.Portugal, 9],
           [Country.France, 10],
           [Country.Ireland, 11],
           [Country.Switzerland, 12],
           [Country.Luxembourg, 13],
           [Country.Belgium, 14],
           [Country.Yugoslavia, 14],
           [Country.Austria, 16],
           [Country.Norway, 17],
           [Country.Malta, 18]]

esc1972 = [[Country.Luxembourg, 1],
           [Country.United_Kingdom, 2],
           [Country.Germany, 3],
           [Country.Netherlands, 4],
           [Country.Austria, 5],
           [Country.Italy, 6],
           [Country.Portugal, 7],
           [Country.Switzerland, 8],
           [Country.Yugoslavia, 9],
           [Country.Spain, 10],
           [Country.France, 11],
           [Country.Finland, 12],
           [Country.Sweden, 13],
           [Country.Norway, 14],
           [Country.Ireland, 15],
           [Country.Monaco, 16],
           [Country.Belgium, 17],
           [Country.Malta, 18]]

esc1973 = [[Country.Luxembourg, 1],
           [Country.Spain, 2],
           [Country.United_Kingdom, 3],
           [Country.Israel, 4],
           [Country.Sweden, 5],
           [Country.Finland, 6],
           [Country.Norway, 7],
           [Country.Germany, 8],
           [Country.Monaco, 8],
           [Country.Portugal, 10],
           [Country.Ireland, 10],
           [Country.Switzerland, 12],
           [Country.Italy, 13],
           [Country.Netherlands, 14],
           [Country.Yugoslavia, 15],
           [Country.France, 15],
           [Country.Belgium, 17]]

esc1974 = [[Country.Sweden, 1],
           [Country.Italy, 2],
           [Country.Netherlands, 3],
           [Country.United_Kingdom, 4],
           [Country.Luxembourg, 4],
           [Country.Monaco, 4],
           [Country.Israel, 7],
           [Country.Ireland, 7],
           [Country.Spain, 9],
           [Country.Belgium, 9],
           [Country.Greece, 11],
           [Country.Yugoslavia, 12],
           [Country.Finland, 13],
           [Country.Norway, 14],
           [Country.Germany, 14],
           [Country.Switzerland, 14],
           [Country.Portugal, 14]]

esc1975 = [[Country.Netherlands, 1],
           [Country.United_Kingdom, 2],
           [Country.Italy, 3],
           [Country.France, 4],
           [Country.Luxembourg, 5],
           [Country.Switzerland, 6],
           [Country.Finland, 7],
           [Country.Sweden, 8],
           [Country.Ireland, 9],
           [Country.Spain, 10],
           [Country.Israel, 11],
           [Country.Malta, 12],
           [Country.Yugoslavia, 13],
           [Country.Monaco, 13],
           [Country.Belgium, 15],
           [Country.Portugal, 16],
           [Country.Germany, 17],
           [Country.Norway, 18],
           [Country.Turkey, 19]]

esc1976 = [[Country.United_Kingdom, 1],
           [Country.France, 2],
           [Country.Monaco, 3],
           [Country.Switzerland, 4],
           [Country.Austria, 5],
           [Country.Israel, 6],
           [Country.Italy, 7],
           [Country.Belgium, 8],
           [Country.Netherlands, 9],
           [Country.Ireland, 10],
           [Country.Finland, 11],
           [Country.Portugal, 12],
           [Country.Greece, 13],
           [Country.Luxembourg, 14],
           [Country.Germany, 15],
           [Country.Spain, 16],
           [Country.Yugoslavia, 17],
           [Country.Norway, 18]]

esc1977 = [[Country.France, 1],
           [Country.United_Kingdom, 2],
           [Country.Ireland, 3],
           [Country.Monaco, 4],
           [Country.Greece, 5],
           [Country.Switzerland, 6],
           [Country.Belgium, 7],
           [Country.Germany, 8],
           [Country.Spain, 9],
           [Country.Finland, 10],
           [Country.Israel, 11],
           [Country.Netherlands, 12],
           [Country.Italy, 13],
           [Country.Norway, 14],
           [Country.Portugal, 14],
           [Country.Luxembourg, 16],
           [Country.Austria, 17],
           [Country.Sweden, 18]]

esc1978 = [[Country.Israel, 1],
           [Country.Belgium, 2],
           [Country.France, 3],
           [Country.Monaco, 4],
           [Country.Ireland, 5],
           [Country.Germany, 6],
           [Country.Luxembourg, 7],
           [Country.Greece, 8],
           [Country.Spain, 9],
           [Country.Switzerland, 9],
           [Country.United_Kingdom, 11],
           [Country.Italy, 12],
           [Country.Netherlands, 13],
           [Country.Sweden, 14],
           [Country.Austria, 15],
           [Country.Denmark, 16],
           [Country.Portugal, 17],
           [Country.Finland, 18],
           [Country.Turkey, 18],
           [Country.Norway, 20]]

esc1979 = [[Country.Israel, 1],
           [Country.Spain, 2],
           [Country.France, 3],
           [Country.Germany, 4],
           [Country.Ireland, 5],
           [Country.Denmark, 6],
           [Country.United_Kingdom, 7],
           [Country.Greece, 8],
           [Country.Portugal, 9],
           [Country.Switzerland, 10],
           [Country.Norway, 11],
           [Country.Netherlands, 12],
           [Country.Luxembourg, 13],
           [Country.Finland, 14],
           [Country.Italy, 15],
           [Country.Monaco, 16],
           [Country.Sweden, 17],
           [Country.Belgium, 18],
           [Country.Austria, 18]]

esc1980 = [[Country.Ireland, 1],
           [Country.Germany, 2],
           [Country.United_Kingdom, 3],
           [Country.Switzerland, 4],
           [Country.Netherlands, 5],
           [Country.Italy, 6],
           [Country.Portugal, 7],
           [Country.Austria, 8],
           [Country.Luxembourg, 9],
           [Country.Sweden, 10],
           [Country.France, 11],
           [Country.Spain, 12],
           [Country.Greece, 13],
           [Country.Denmark, 14],
           [Country.Turkey, 15],
           [Country.Norway, 16],
           [Country.Belgium, 17],
           [Country.Morocco, 18],
           [Country.Finland, 19]]

esc1981 = [[Country.United_Kingdom, 1],
           [Country.Germany, 2],
           [Country.France, 3],
           [Country.Switzerland, 4],
           [Country.Ireland, 5],
           [Country.Cyprus, 6],
           [Country.Israel, 7],
           [Country.Greece, 8],
           [Country.Netherlands, 9],
           [Country.Sweden, 10],
           [Country.Luxembourg, 11],
           [Country.Denmark, 11],
           [Country.Belgium, 13],
           [Country.Spain, 14],
           [Country.Yugoslavia, 15],
           [Country.Finland, 16],
           [Country.Austria, 17],
           [Country.Turkey, 18],
           [Country.Portugal, 18],
           [Country.Norway, 20]]

esc1982 = [[Country.Germany, 1],
           [Country.Israel, 2],
           [Country.Switzerland, 3],
           [Country.Belgium, 4],
           [Country.Cyprus, 5],
           [Country.Luxembourg, 6],
           [Country.United_Kingdom, 7],
           [Country.Sweden, 8],
           [Country.Austria, 9],
           [Country.Spain, 10],
           [Country.Ireland, 11],
           [Country.Norway, 12],
           [Country.Portugal, 13],
           [Country.Yugoslavia, 14],
           [Country.Turkey, 15],
           [Country.Netherlands, 16],
           [Country.Denmark, 17],
           [Country.Finland, 20]]

esc1983 = [[Country.Luxembourg, 1],
           [Country.Israel, 2],
           [Country.Sweden, 3],
           [Country.Yugoslavia, 4],
           [Country.Germany, 5],
           [Country.United_Kingdom, 6],
           [Country.Netherlands, 7],
           [Country.France, 8],
           [Country.Norway, 9],
           [Country.Austria, 9],
           [Country.Italy, 11],
           [Country.Finland, 11],
           [Country.Portugal, 13],
           [Country.Greece, 14],
           [Country.Switzerland, 15],
           [Country.Cyprus, 16],
           [Country.Denmark, 17],
           [Country.Belgium, 18],
           [Country.Turkey, 19],
           [Country.Spain, 19]]

esc1984 = [[Country.Sweden, 1],
           [Country.Ireland, 2],
           [Country.Spain, 3],
           [Country.Denmark, 4],
           [Country.Belgium, 5],
           [Country.Italy, 5],
           [Country.United_Kingdom, 7],
           [Country.France, 8],
           [Country.Finland, 9],
           [Country.Luxembourg, 9],
           [Country.Portugal, 11],
           [Country.Turkey, 12],
           [Country.Netherlands, 13],
           [Country.Germany, 13],
           [Country.Cyprus, 15],
           [Country.Switzerland, 16],
           [Country.Norway, 17],
           [Country.Yugoslavia, 18],
           [Country.Austria, 19]]

esc1985 = [[Country.Norway, 1],
           [Country.Germany, 2],
           [Country.Sweden, 3],
           [Country.United_Kingdom, 4],
           [Country.Israel, 5],
           [Country.Ireland, 6],
           [Country.Italy, 7],
           [Country.Austria, 8],
           [Country.Finland, 9],
           [Country.France, 10],
           [Country.Denmark, 11],
           [Country.Switzerland, 12],
           [Country.Luxembourg, 13],
           [Country.Spain, 14],
           [Country.Turkey, 14],
           [Country.Cyprus, 16],
           [Country.Greece, 16],
           [Country.Portugal, 18],
           [Country.Belgium, 19]]

esc1986 = [[Country.Belgium, 1],
           [Country.Switzerland, 2],
           [Country.Luxembourg, 3],
           [Country.Ireland, 4],
           [Country.Sweden, 5],
           [Country.Denmark, 6],
           [Country.United_Kingdom, 7],
           [Country.Germany, 8],
           [Country.Turkey, 9],
           [Country.Spain, 10],
           [Country.Yugoslavia, 11],
           [Country.Norway, 12],
           [Country.Netherlands, 13],
           [Country.Portugal, 14],
           [Country.Finland, 15],
           [Country.Iceland, 16],
           [Country.France, 17],
           [Country.Austria, 18],
           [Country.Israel, 19],
           [Country.Cyprus, 20]]

esc1987 = [[Country.Ireland, 1],
           [Country.Germany, 2],
           [Country.Italy, 3],
           [Country.Yugoslavia, 4],
           [Country.Netherlands, 5],
           [Country.Denmark, 5],
           [Country.Cyprus, 7],
           [Country.Israel, 8],
           [Country.Norway, 9],
           [Country.Greece, 10],
           [Country.Belgium, 11],
           [Country.Sweden, 12],
           [Country.United_Kingdom, 13],
           [Country.France, 14],
           [Country.Finland, 15],
           [Country.Iceland, 16],
           [Country.Switzerland, 17],
           [Country.Portugal, 18],
           [Country.Spain, 19],
           [Country.Austria, 20],
           [Country.Luxembourg, 21],
           [Country.Turkey, 22]]

esc1988 = [[Country.Switzerland, 1],
           [Country.United_Kingdom, 2],
           [Country.Denmark, 3],
           [Country.Luxembourg, 4],
           [Country.Norway, 5],
           [Country.Yugoslavia, 6],
           [Country.Israel, 7],
           [Country.Ireland, 8],
           [Country.Netherlands, 9],
           [Country.France, 10],
           [Country.Spain, 11],
           [Country.Sweden, 12],
           [Country.Italy, 12],
           [Country.Germany, 14],
           [Country.Turkey, 15],
           [Country.Iceland, 16],
           [Country.Greece, 17],
           [Country.Belgium, 18],
           [Country.Portugal, 19],
           [Country.Finland, 20],
           [Country.Austria, 21]]

esc1989 = [[Country.Yugoslavia, 1],
           [Country.United_Kingdom, 2],
           [Country.Denmark, 3],
           [Country.Sweden, 4],
           [Country.Austria, 5],
           [Country.Spain, 6],
           [Country.Finland, 7],
           [Country.France, 8],
           [Country.Italy, 9],
           [Country.Greece, 9],
           [Country.Cyprus, 11],
           [Country.Israel, 12],
           [Country.Switzerland, 13],
           [Country.Germany, 14],
           [Country.Netherlands, 15],
           [Country.Portugal, 16],
           [Country.Norway, 17],
           [Country.Ireland, 18],
           [Country.Belgium, 19],
           [Country.Luxembourg, 20],
           [Country.Turkey, 21],
           [Country.Iceland, 22]]

esc1990 = [[Country.Italy, 1],
           [Country.France, 2],
           [Country.Ireland, 2],
           [Country.Iceland, 4],
           [Country.Spain, 5],
           [Country.United_Kingdom, 6],
           [Country.Yugoslavia, 7],
           [Country.Denmark, 8],
           [Country.Germany, 9],
           [Country.Austria, 10],
           [Country.Switzerland, 11],
           [Country.Belgium, 12],
           [Country.Luxembourg, 13],
           [Country.Cyprus, 14],
           [Country.Netherlands, 15],
           [Country.Sweden, 16],
           [Country.Turkey, 17],
           [Country.Israel, 18],
           [Country.Greece, 19],
           [Country.Portugal, 20],
           [Country.Norway, 21],
           [Country.Finland, 21]]

esc1991 = [[Country.Sweden, 1],
           [Country.France, 2],
           [Country.Israel, 3],
           [Country.Spain, 4],
           [Country.Switzerland, 5],
           [Country.Malta, 6],
           [Country.Italy, 7],
           [Country.Portugal, 8],
           [Country.Cyprus, 9],
           [Country.Ireland, 10],
           [Country.United_Kingdom, 10],
           [Country.Turkey, 12],
           [Country.Greece, 13],
           [Country.Luxembourg, 14],
           [Country.Iceland, 15],
           [Country.Belgium, 16],
           [Country.Norway, 17],
           [Country.Germany, 18],
           [Country.Denmark, 19],
           [Country.Finland, 20],
           [Country.Yugoslavia, 21],
           [Country.Austria, 22]]

esc1992 = [[Country.Ireland, 1],
           [Country.United_Kingdom, 2],
           [Country.Malta, 3],
           [Country.Italy, 4],
           [Country.Greece, 5],
           [Country.Israel, 6],
           [Country.Iceland, 7],
           [Country.France, 8],
           [Country.Netherlands, 9],
           [Country.Austria, 10],
           [Country.Cyprus, 11],
           [Country.Denmark, 12],
           [Country.Yugoslavia, 13],
           [Country.Spain, 14],
           [Country.Switzerland, 15],
           [Country.Germany, 16],
           [Country.Portugal, 17],
           [Country.Norway, 18],
           [Country.Turkey, 19],
           [Country.Belgium, 20],
           [Country.Luxembourg, 21],
           [Country.Sweden, 22],
           [Country.Finland, 23]]

esc1993 = [[Country.Ireland, 1],
           [Country.United_Kingdom, 2],
           [Country.Switzerland, 3],
           [Country.France, 4],
           [Country.Norway, 5],
           [Country.Netherlands, 6],
           [Country.Sweden, 7],
           [Country.Malta, 8],
           [Country.Greece, 9],
           [Country.Portugal, 10],
           [Country.Spain, 11],
           [Country.Italy, 12],
           [Country.Iceland, 13],
           [Country.Austria, 14],
           [Country.Croatia, 15],
           [Country.Bosnia_and_Herzegovina, 16],
           [Country.Finland, 17],
           [Country.Germany, 18],
           [Country.Cyprus, 19],
           [Country.Luxembourg, 20],
           [Country.Turkey, 21],
           [Country.Denmark, 22],
           [Country.Slovenia, 23],
           [Country.Israel, 24],
           [Country.Belgium, 25]]

esc1994 = [[Country.Ireland, 1],
           [Country.Poland, 2],
           [Country.Germany, 3],
           [Country.Hungary, 4],
           [Country.Malta, 5],
           [Country.Norway, 6],
           [Country.France, 7],
           [Country.Portugal, 8],
           [Country.Russia, 9],
           [Country.United_Kingdom, 10],
           [Country.Cyprus, 11],
           [Country.Iceland, 12],
           [Country.Sweden, 13],
           [Country.Greece, 14],
           [Country.Bosnia_and_Herzegovina, 15],
           [Country.Croatia, 16],
           [Country.Austria, 17],
           [Country.Spain, 18],
           [Country.Switzerland, 19],
           [Country.Slovakia, 19],
           [Country.Romania, 21],
           [Country.Finland, 22],
           [Country.Netherlands, 23],
           [Country.Estonia, 24],
           [Country.Lithuania, 25]]

esc1995 = [[Country.Norway, 1],
           [Country.Spain, 2],
           [Country.Sweden, 3],
           [Country.France, 4],
           [Country.Denmark, 5],
           [Country.Croatia, 6],
           [Country.Slovenia, 7],
           [Country.Israel, 8],
           [Country.Cyprus, 9],
           [Country.United_Kingdom, 10],
           [Country.Malta, 10],
           [Country.Greece, 12],
           [Country.Austria, 13],
           [Country.Ireland, 14],
           [Country.Iceland, 15],
           [Country.Turkey, 16],
           [Country.Russia, 17],
           [Country.Poland, 18],
           [Country.Bosnia_and_Herzegovina, 19],
           [Country.Belgium, 20],
           [Country.Portugal, 21],
           [Country.Hungary, 22],
           [Country.Germany, 23]]

esc1996 = [[Country.Ireland, 1],
           [Country.Norway, 2],
           [Country.Sweden, 3],
           [Country.Croatia, 4],
           [Country.Estonia, 5],
           [Country.Portugal, 6],
           [Country.Netherlands, 7],
           [Country.United_Kingdom, 8],
           [Country.Cyprus, 9],
           [Country.Malta, 10],
           [Country.Austria, 10],
           [Country.Turkey, 12],
           [Country.Iceland, 13],
           [Country.Greece, 14],
           [Country.Poland, 15],
           [Country.Switzerland, 16],
           [Country.Belgium, 16],
           [Country.Slovakia, 18],
           [Country.France, 19],
           [Country.Spain, 20],
           [Country.Slovenia, 21],
           [Country.Bosnia_and_Herzegovina, 22],
           [Country.Finland, 23]]

esc1997 = [[Country.United_Kingdom, 1],
           [Country.Ireland, 2],
           [Country.Turkey, 3],
           [Country.Italy, 4],
           [Country.Cyprus, 5],
           [Country.Spain, 6],
           [Country.France, 7],
           [Country.Estonia, 8],
           [Country.Malta, 9],
           [Country.Slovenia, 10],
           [Country.Poland, 11],
           [Country.Greece, 12],
           [Country.Hungary, 12],
           [Country.Sweden, 14],
           [Country.Russia, 15],
           [Country.Denmark, 16],
           [Country.Croatia, 17],
           [Country.Germany, 18],
           [Country.Bosnia_and_Herzegovina, 18],
           [Country.Iceland, 20],
           [Country.Austria, 21],
           [Country.Switzerland, 22],
           [Country.Netherlands, 22],
           [Country.Norway, 24],
           [Country.Portugal, 24]]

esc1998 = [[Country.Israel, 1],
           [Country.United_Kingdom, 2],
           [Country.Malta, 3],
           [Country.Netherlands, 4],
           [Country.Croatia, 5],
           [Country.Belgium, 6],
           [Country.Germany, 7],
           [Country.Norway, 8],
           [Country.Ireland, 9],
           [Country.Sweden, 10],
           [Country.Cyprus, 11],
           [Country.Portugal, 12],
           [Country.Estonia, 12],
           [Country.Turkey, 14],
           [Country.Finland, 15],
           [Country.Spain, 16],
           [Country.Poland, 17],
           [Country.Slovenia, 18],
           [Country.North_Macedonia, 19],
           [Country.Greece, 20],
           [Country.Slovakia, 21],
           [Country.Romania, 22],
           [Country.Hungary, 23],
           [Country.France, 24],
           [Country.Switzerland, 25]]

esc1999 = [[Country.Sweden, 1],
           [Country.Iceland, 2],
           [Country.Germany, 3],
           [Country.Croatia, 4],
           [Country.Israel, 5],
           [Country.Estonia, 6],
           [Country.Bosnia_and_Herzegovina, 7],
           [Country.Denmark, 8],
           [Country.Netherlands, 8],
           [Country.Austria, 10],
           [Country.Slovenia, 11],
           [Country.Belgium, 12],
           [Country.United_Kingdom, 12],
           [Country.Norway, 14],
           [Country.Malta, 15],
           [Country.Turkey, 16],
           [Country.Ireland, 17],
           [Country.Poland, 18],
           [Country.France, 19],
           [Country.Lithuania, 20],
           [Country.Portugal, 21],
           [Country.Cyprus, 22],
           [Country.Spain, 23]]

esc2000 = [[Country.Denmark, 1],
           [Country.Russia, 2],
           [Country.Latvia, 3],
           [Country.Estonia, 4],
           [Country.Germany, 5],
           [Country.Ireland, 6],
           [Country.Sweden, 7],
           [Country.Malta, 8],
           [Country.Croatia, 9],
           [Country.Turkey, 10],
           [Country.Norway, 11],
           [Country.Iceland, 12],
           [Country.Netherlands, 13],
           [Country.Austria, 14],
           [Country.North_Macedonia, 15],
           [Country.United_Kingdom, 16],
           [Country.Romania, 17],
           [Country.Spain, 18],
           [Country.Finland, 18],
           [Country.Switzerland, 20],
           [Country.Cyprus, 21],
           [Country.Israel, 22],
           [Country.France, 23],
           [Country.Belgium, 24]]

esc2001 = [[Country.Estonia, 1],
           [Country.Denmark, 2],
           [Country.Greece, 3],
           [Country.France, 4],
           [Country.Sweden, 5],
           [Country.Spain, 6],
           [Country.Slovenia, 7],
           [Country.Germany, 8],
           [Country.Malta, 9],
           [Country.Croatia, 10],
           [Country.Turkey, 11],
           [Country.Russia, 12],
           [Country.Lithuania, 13],
           [Country.Bosnia_and_Herzegovina, 14],
           [Country.United_Kingdom, 15],
           [Country.Israel, 16],
           [Country.Portugal, 17],
           [Country.Netherlands, 18],
           [Country.Latvia, 18],
           [Country.Poland, 20],
           [Country.Ireland, 21],
           [Country.Iceland, 22],
           [Country.Norway, 22]]

esc2002 = [[Country.Latvia, 1],
           [Country.Malta, 2],
           [Country.United_Kingdom, 3],
           [Country.Estonia, 3],
           [Country.France, 5],
           [Country.Cyprus, 6],
           [Country.Spain, 7],
           [Country.Sweden, 8],
           [Country.Romania, 9],
           [Country.Russia, 10],
           [Country.Croatia, 11],
           [Country.Israel, 12],
           [Country.Bosnia_and_Herzegovina, 13],
           [Country.Belarus, 13],
           [Country.Slovenia, 13],
           [Country.Turkey, 16],
           [Country.Greece, 17],
           [Country.Austria, 18],
           [Country.North_Macedonia, 19],
           [Country.Finland, 20],
           [Country.Germany, 21],
           [Country.Switzerland, 22],
           [Country.Lithuania, 23],
           [Country.Denmark, 24]]

esc2003 = [[Country.Turkey, 1],
           [Country.Belgium, 2],
           [Country.Russia, 3],
           [Country.Norway, 4],
           [Country.Sweden, 5],
           [Country.Austria, 6],
           [Country.Poland, 7],
           [Country.Iceland, 8],
           [Country.Spain, 8],
           [Country.Romania, 10],
           [Country.Ireland, 11],
           [Country.Germany, 11],
           [Country.Netherlands, 13],
           [Country.Ukraine, 14],
           [Country.Croatia, 15],
           [Country.Bosnia_and_Herzegovina, 16],
           [Country.Greece, 17],
           [Country.France, 18],
           [Country.Israel, 19],
           [Country.Cyprus, 20],
           [Country.Estonia, 21],
           [Country.Portugal, 22],
           [Country.Slovenia, 23],
           [Country.Latvia, 24],
           [Country.Malta, 25],
           [Country.United_Kingdom, 26]]

esc2004 = [[Country.Ukraine, 1],
           [Country.Serbia_and_Montenegro, 2],
           [Country.Greece, 3],
           [Country.Turkey, 4],
           [Country.Cyprus, 5],
           [Country.Sweden, 5],
           [Country.Albania, 7],
           [Country.Germany, 8],
           [Country.Bosnia_and_Herzegovina, 9],
           [Country.Spain, 10],
           [Country.Russia, 11],
           [Country.Malta, 12],
           [Country.Croatia, 12],
           [Country.North_Macedonia, 14],
           [Country.France, 15],
           [Country.United_Kingdom, 16],
           [Country.Poland, 17],
           [Country.Romania, 18],
           [Country.Iceland, 19],
           [Country.Netherlands, 20],
           [Country.Austria, 33],
           [Country.Belgium, 34],
           [Country.Ireland, 34],
           [Country.Norway, 36],
           [Country.Estonia, 25],
           [Country.Israel, 25],
           [Country.Denmark, 27],
           [Country.Finland, 28],
           [Country.Portugal, 29],
           [Country.Lithuania, 30],
           [Country.Latvia, 31],
           [Country.Andorra, 32],
           [Country.Belarus, 33],
           [Country.Monaco, 33],
           [Country.Slovenia, 35],
           [Country.Switzerland, 36]]

esc2005 = [[Country.Greece, 1],
           [Country.Malta, 2],
           [Country.Romania, 3],
           [Country.Israel, 4],
           [Country.Latvia, 5],
           [Country.Moldova, 6],
           [Country.Serbia_and_Montenegro, 7],
           [Country.Switzerland, 8],
           [Country.Norway, 9],
           [Country.Denmark, 9],
           [Country.Croatia, 11],
           [Country.Hungary, 12],
           [Country.Turkey, 13],
           [Country.Bosnia_and_Herzegovina, 14],
           [Country.Russia, 15],
           [Country.Albania, 16],
           [Country.North_Macedonia, 17],
           [Country.Cyprus, 26],
           [Country.Sweden, 28],
           [Country.Ukraine, 28],
           [Country.Spain, 32],
           [Country.United_Kingdom, 34],
           [Country.France, 36],
           [Country.Germany, 38],
           [Country.Poland, 18],
           [Country.Slovenia, 19],
           [Country.Belarus, 20],
           [Country.Netherlands, 21],
           [Country.Ireland, 21],
           [Country.Iceland, 23],
           [Country.Portugal, 24],
           [Country.Finland, 25],
           [Country.Bulgaria, 26],
           [Country.Estonia, 28],
           [Country.Austria, 31],
           [Country.Belgium, 32],
           [Country.Andorra, 34],
           [Country.Monaco, 36],
           [Country.Lithuania, 38]]

esc2006 = [[Country.Finland, 1],
           [Country.Russia, 2],
           [Country.Bosnia_and_Herzegovina, 3],
           [Country.Romania, 4],
           [Country.Sweden, 5],
           [Country.Lithuania, 6],
           [Country.Ukraine, 7],
           [Country.Armenia, 8],
           [Country.Greece, 9],
           [Country.Ireland, 10],
           [Country.Turkey, 11],
           [Country.North_Macedonia, 12],
           [Country.Croatia, 14],
           [Country.Norway, 16],
           [Country.Germany, 16],
           [Country.Switzerland, 20],
           [Country.Latvia, 20],
           [Country.Denmark, 24],
           [Country.United_Kingdom, 26],
           [Country.Moldova, 28],
           [Country.Spain, 30],
           [Country.France, 32],
           [Country.Israel, 34],
           [Country.Malta, 36],
           [Country.Poland, 13],
           [Country.Belgium, 14],
           [Country.Iceland, 16],
           [Country.Albania, 19],
           [Country.Cyprus, 20],
           [Country.Slovenia, 23],
           [Country.Bulgaria, 24],
           [Country.Estonia, 26],
           [Country.Portugal, 28],
           [Country.Netherlands, 30],
           [Country.Monaco, 32],
           [Country.Belarus, 34],
           [Country.Andorra, 36]]

esc2007 = [[Country.Serbia, 1],
           [Country.Ukraine, 2],
           [Country.Russia, 3],
           [Country.Turkey, 4],
           [Country.Bulgaria, 5],
           [Country.Belarus, 6],
           [Country.Greece, 7],
           [Country.Armenia, 8],
           [Country.Hungary, 9],
           [Country.Moldova, 10],
           [Country.Bosnia_and_Herzegovina, 11],
           [Country.Georgia, 12],
           [Country.Romania, 13],
           [Country.North_Macedonia, 14],
           [Country.Slovenia, 15],
           [Country.Latvia, 16],
           [Country.Finland, 27],
           [Country.Sweden, 29],
           [Country.Germany, 32],
           [Country.Spain, 33],
           [Country.Lithuania, 35],
           [Country.France, 37],
           [Country.United_Kingdom, 37],
           [Country.Ireland, 41],
           [Country.Portugal, 17],
           [Country.Andorra, 18],
           [Country.Iceland, 19],
           [Country.Poland, 20],
           [Country.Cyprus, 21],
           [Country.Croatia, 22],
           [Country.Albania, 23],
           [Country.Norway, 24],
           [Country.Denmark, 25],
           [Country.Switzerland, 26],
           [Country.Netherlands, 27],
           [Country.Montenegro, 29],
           [Country.Estonia, 29],
           [Country.Israel, 33],
           [Country.Malta, 35],
           [Country.Belgium, 37],
           [Country.Austria, 40],
           [Country.Czech_Republic, 41]]

esc2008 = [[Country.Russia, 1],
           [Country.Ukraine, 2],
           [Country.Greece, 3],
           [Country.Armenia, 4],
           [Country.Norway, 5],
           [Country.Serbia, 6],
           [Country.Turkey, 7],
           [Country.Azerbaijan, 8],
           [Country.Israel, 9],
           [Country.Bosnia_and_Herzegovina, 10],
           [Country.Georgia, 11],
           [Country.Latvia, 12],
           [Country.Portugal, 13],
           [Country.Iceland, 14],
           [Country.Denmark, 15],
           [Country.Spain, 16],
           [Country.Albania, 17],
           [Country.Sweden, 18],
           [Country.France, 19],
           [Country.Romania, 20],
           [Country.Croatia, 21],
           [Country.Finland, 22],
           [Country.Germany, 23],
           [Country.Poland, 24],
           [Country.United_Kingdom, 42],
           [Country.North_Macedonia, 25],
           [Country.Bulgaria, 26],
           [Country.Switzerland, 27],
           [Country.Malta, 28],
           [Country.Slovenia, 29],
           [Country.Moldova, 30],
           [Country.Cyprus, 31],
           [Country.Lithuania, 32],
           [Country.Netherlands, 33],
           [Country.Belarus, 34],
           [Country.Montenegro, 35],
           [Country.Ireland, 36],
           [Country.Andorra, 37],
           [Country.Belgium, 38],
           [Country.Czech_Republic, 39],
           [Country.Estonia, 40],
           [Country.Hungary, 41],
           [Country.San_Marino, 42]]

esc2009 = [[Country.Norway, 1],
           [Country.Iceland, 2],
           [Country.Azerbaijan, 3],
           [Country.Turkey, 4],
           [Country.United_Kingdom, 5],
           [Country.Estonia, 6],
           [Country.Greece, 7],
           [Country.France, 8],
           [Country.Bosnia_and_Herzegovina, 9],
           [Country.Armenia, 10],
           [Country.Russia, 11],
           [Country.Ukraine, 12],
           [Country.Denmark, 13],
           [Country.Moldova, 14],
           [Country.Portugal, 15],
           [Country.Israel, 16],
           [Country.Albania, 17],
           [Country.Croatia, 18],
           [Country.Romania, 19],
           [Country.Germany, 20],
           [Country.Sweden, 21],
           [Country.Malta, 22],
           [Country.Lithuania, 23],
           [Country.Spain, 24],
           [Country.Finland, 25],
           [Country.Serbia, 26],
           [Country.Ireland, 27],
           [Country.North_Macedonia, 28],
           [Country.Montenegro, 29],
           [Country.Poland, 30],
           [Country.Cyprus, 31],
           [Country.Belarus, 32],
           [Country.Switzerland, 33],
           [Country.Hungary, 34],
           [Country.Slovenia, 35],
           [Country.Netherlands, 36],
           [Country.Andorra, 37],
           [Country.Slovakia, 38],
           [Country.Bulgaria, 39],
           [Country.Latvia, 40],
           [Country.Belgium, 41],
           [Country.Czech_Republic, 42]]

esc2010 = [[Country.Germany, 1],
           [Country.Turkey, 2],
           [Country.Romania, 3],
           [Country.Denmark, 4],
           [Country.Azerbaijan, 5],
           [Country.Belgium, 6],
           [Country.Armenia, 7],
           [Country.Greece, 8],
           [Country.Georgia, 9],
           [Country.Ukraine, 10],
           [Country.Russia, 11],
           [Country.France, 12],
           [Country.Serbia, 13],
           [Country.Israel, 14],
           [Country.Spain, 15],
           [Country.Albania, 16],
           [Country.Bosnia_and_Herzegovina, 17],
           [Country.Portugal, 18],
           [Country.Iceland, 19],
           [Country.Norway, 20],
           [Country.Cyprus, 21],
           [Country.Moldova, 22],
           [Country.Ireland, 23],
           [Country.Belarus, 24],
           [Country.United_Kingdom, 38],
           [Country.Sweden, 25],
           [Country.Finland, 26],
           [Country.Lithuania, 27],
           [Country.Malta, 28],
           [Country.Poland, 29],
           [Country.Estonia, 30],
           [Country.North_Macedonia, 31],
           [Country.Croatia, 32],
           [Country.Netherlands, 33],
           [Country.Slovakia, 34],
           [Country.Bulgaria, 35],
           [Country.Latvia, 36],
           [Country.Slovenia, 37],
           [Country.Switzerland, 38]]

esc2011 = [[Country.Azerbaijan, 1],
           [Country.Italy, 2],
           [Country.Sweden, 3],
           [Country.Ukraine, 4],
           [Country.Denmark, 5],
           [Country.Bosnia_and_Herzegovina, 6],
           [Country.Greece, 7],
           [Country.Ireland, 8],
           [Country.Georgia, 9],
           [Country.Germany, 10],
           [Country.United_Kingdom, 11],
           [Country.Moldova, 12],
           [Country.Slovenia, 13],
           [Country.Serbia, 14],
           [Country.France, 15],
           [Country.Russia, 16],
           [Country.Romania, 17],
           [Country.Austria, 18],
           [Country.Lithuania, 19],
           [Country.Iceland, 20],
           [Country.Finland, 21],
           [Country.Hungary, 22],
           [Country.Spain, 23],
           [Country.Estonia, 24],
           [Country.Switzerland, 25],
           [Country.Malta, 26],
           [Country.Armenia, 27],
           [Country.Belgium, 28],
           [Country.Turkey, 29],
           [Country.Albania, 30],
           [Country.Bulgaria, 31],
           [Country.Slovakia, 32],
           [Country.Belarus, 33],
           [Country.Croatia, 34],
           [Country.Israel, 35],
           [Country.North_Macedonia, 36],
           [Country.San_Marino, 37],
           [Country.Norway, 38],
           [Country.Latvia, 39],
           [Country.Portugal, 40],
           [Country.Poland, 41],
           [Country.Cyprus, 42],
           [Country.Netherlands, 43]]

esc2012 = [[Country.Sweden, 1],
           [Country.Russia, 2],
           [Country.Serbia, 3],
           [Country.Azerbaijan, 4],
           [Country.Albania, 5],
           [Country.Estonia, 6],
           [Country.Turkey, 7],
           [Country.Germany, 8],
           [Country.Italy, 9],
           [Country.Spain, 10],
           [Country.Moldova, 11],
           [Country.Romania, 12],
           [Country.North_Macedonia, 13],
           [Country.Lithuania, 14],
           [Country.Ukraine, 15],
           [Country.Cyprus, 16],
           [Country.Greece, 17],
           [Country.Bosnia_and_Herzegovina, 18],
           [Country.Ireland, 19],
           [Country.Iceland, 20],
           [Country.Malta, 21],
           [Country.France, 22],
           [Country.Denmark, 23],
           [Country.Hungary, 24],
           [Country.United_Kingdom, 25],
           [Country.Norway, 26],
           [Country.Bulgaria, 27],
           [Country.Switzerland, 28],
           [Country.Croatia, 29],
           [Country.Finland, 30],
           [Country.Portugal, 31],
           [Country.Georgia, 32],
           [Country.Netherlands, 33],
           [Country.Belarus, 34],
           [Country.Israel, 35],
           [Country.San_Marino, 36],
           [Country.Slovenia, 37],
           [Country.Slovakia, 38],
           [Country.Montenegro, 39],
           [Country.Latvia, 40],
           [Country.Belgium, 41],
           [Country.Austria, 42]]

esc2013 = [[Country.Denmark, 1],
           [Country.Azerbaijan, 2],
           [Country.Ukraine, 3],
           [Country.Norway, 4],
           [Country.Russia, 5],
           [Country.Greece, 6],
           [Country.Italy, 7],
           [Country.Malta, 8],
           [Country.Netherlands, 9],
           [Country.Hungary, 10],
           [Country.Moldova, 11],
           [Country.Belgium, 12],
           [Country.Romania, 13],
           [Country.Sweden, 14],
           [Country.Georgia, 15],
           [Country.Belarus, 16],
           [Country.Iceland, 17],
           [Country.Armenia, 18],
           [Country.United_Kingdom, 19],
           [Country.Estonia, 20],
           [Country.Germany, 21],
           [Country.Lithuania, 22],
           [Country.France, 23],
           [Country.Finland, 24],
           [Country.Spain, 25],
           [Country.Ireland, 26],
           [Country.Serbia, 27],
           [Country.San_Marino, 28],
           [Country.Bulgaria, 29],
           [Country.Montenegro, 30],
           [Country.Switzerland, 31],
           [Country.Croatia, 32],
           [Country.Israel, 33],
           [Country.Albania, 34],
           [Country.Austria, 35],
           [Country.North_Macedonia, 36],
           [Country.Latvia, 37],
           [Country.Cyprus, 38],
           [Country.Slovenia, 39]]

esc2014 = [[Country.Austria, 1],
           [Country.Netherlands, 2],
           [Country.Sweden, 3],
           [Country.Armenia, 4],
           [Country.Hungary, 5],
           [Country.Ukraine, 6],
           [Country.Russia, 7],
           [Country.Norway, 8],
           [Country.Denmark, 9],
           [Country.Spain, 10],
           [Country.Finland, 11],
           [Country.Romania, 12],
           [Country.Switzerland, 13],
           [Country.Poland, 14],
           [Country.Iceland, 15],
           [Country.Belarus, 16],
           [Country.United_Kingdom, 17],
           [Country.Germany, 18],
           [Country.Montenegro, 19],
           [Country.Greece, 20],
           [Country.Italy, 21],
           [Country.Azerbaijan, 22],
           [Country.Malta, 23],
           [Country.San_Marino, 24],
           [Country.Slovenia, 25],
           [Country.France, 36],
           [Country.Portugal, 26],
           [Country.Lithuania, 27],
           [Country.Ireland, 28],
           [Country.Estonia, 29],
           [Country.North_Macedonia, 30],
           [Country.Latvia, 31],
           [Country.Belgium, 32],
           [Country.Albania, 33],
           [Country.Israel, 34],
           [Country.Georgia, 35],
           [Country.Moldova, 36]]

esc2015 = [[Country.Sweden, 1],
           [Country.Russia, 2],
           [Country.Italy, 3],
           [Country.Belgium, 4],
           [Country.Australia, 5],
           [Country.Latvia, 6],
           [Country.Estonia, 7],
           [Country.Norway, 8],
           [Country.Israel, 9],
           [Country.Serbia, 10],
           [Country.Georgia, 11],
           [Country.Azerbaijan, 12],
           [Country.Montenegro, 13],
           [Country.Slovenia, 14],
           [Country.Romania, 15],
           [Country.Armenia, 16],
           [Country.Albania, 17],
           [Country.Lithuania, 18],
           [Country.Greece, 19],
           [Country.Hungary, 20],
           [Country.Spain, 21],
           [Country.Cyprus, 22],
           [Country.Poland, 23],
           [Country.United_Kingdom, 33],
           [Country.France, 35],
           [Country.Austria, 37],
           [Country.Germany, 39],
           [Country.Moldova, 24],
           [Country.Malta, 25],
           [Country.Belarus, 26],
           [Country.Ireland, 27],
           [Country.Denmark, 28],
           [Country.Netherlands, 29],
           [Country.Czech_Republic, 30],
           [Country.North_Macedonia, 31],
           [Country.Portugal, 32],
           [Country.Iceland, 33],
           [Country.Finland, 35],
           [Country.San_Marino, 37],
           [Country.Switzerland, 39]]

esc2016 = [[Country.Ukraine, 1],
           [Country.Australia, 2],
           [Country.Russia, 3],
           [Country.Bulgaria, 4],
           [Country.Sweden, 5],
           [Country.France, 6],
           [Country.Armenia, 7],
           [Country.Poland, 8],
           [Country.Lithuania, 9],
           [Country.Belgium, 10],
           [Country.Netherlands, 11],
           [Country.Malta, 12],
           [Country.Austria, 13],
           [Country.Israel, 14],
           [Country.Latvia, 15],
           [Country.Italy, 16],
           [Country.Azerbaijan, 17],
           [Country.Serbia, 18],
           [Country.Hungary, 19],
           [Country.Georgia, 20],
           [Country.Cyprus, 21],
           [Country.Spain, 22],
           [Country.Croatia, 23],
           [Country.United_Kingdom, 24],
           [Country.Czech_Republic, 25],
           [Country.Germany, 41],
           [Country.Bosnia_and_Herzegovina, 26],
           [Country.North_Macedonia, 27],
           [Country.Belarus, 28],
           [Country.San_Marino, 29],
           [Country.Norway, 30],
           [Country.Montenegro, 31],
           [Country.Slovenia, 32],
           [Country.Iceland, 33],
           [Country.Finland, 34],
           [Country.Ireland, 35],
           [Country.Albania, 36],
           [Country.Greece, 37],
           [Country.Denmark, 38],
           [Country.Moldova, 39],
           [Country.Switzerland, 40],
           [Country.Estonia, 41]]

esc2017 = [[Country.Portugal, 1],
           [Country.Bulgaria, 2],
           [Country.Moldova, 3],
           [Country.Belgium, 4],
           [Country.Sweden, 5],
           [Country.Italy, 6],
           [Country.Romania, 7],
           [Country.Hungary, 8],
           [Country.Australia, 9],
           [Country.Norway, 10],
           [Country.Netherlands, 11],
           [Country.France, 12],
           [Country.Croatia, 13],
           [Country.Azerbaijan, 14],
           [Country.United_Kingdom, 15],
           [Country.Austria, 16],
           [Country.Belarus, 17],
           [Country.Armenia, 18],
           [Country.Greece, 19],
           [Country.Denmark, 20],
           [Country.Cyprus, 21],
           [Country.Poland, 22],
           [Country.Israel, 23],
           [Country.Ukraine, 37],
           [Country.Germany, 39],
           [Country.Spain, 41],
           [Country.Georgia, 24],
           [Country.Serbia, 25],
           [Country.Switzerland, 26],
           [Country.Finland, 27],
           [Country.Ireland, 28],
           [Country.Estonia, 29],
           [Country.Czech_Republic, 30],
           [Country.Albania, 31],
           [Country.North_Macedonia, 32],
           [Country.Iceland, 33],
           [Country.Montenegro, 34],
           [Country.Malta, 35],
           [Country.Lithuania, 36],
           [Country.Slovenia, 37],
           [Country.Latvia, 39],
           [Country.San_Marino, 41]]

esc2018 = [[Country.Israel, 1],
           [Country.Cyprus, 2],
           [Country.Austria, 3],
           [Country.Germany, 4],
           [Country.Italy, 5],
           [Country.Czech_Republic, 6],
           [Country.Sweden, 7],
           [Country.Estonia, 8],
           [Country.Denmark, 9],
           [Country.Moldova, 10],
           [Country.Albania, 11],
           [Country.Lithuania, 12],
           [Country.France, 13],
           [Country.Bulgaria, 14],
           [Country.Norway, 15],
           [Country.Ireland, 16],
           [Country.Ukraine, 17],
           [Country.Netherlands, 18],
           [Country.Serbia, 19],
           [Country.Australia, 20],
           [Country.Hungary, 21],
           [Country.Slovenia, 22],
           [Country.Spain, 23],
           [Country.United_Kingdom, 24],
           [Country.Finland, 25],
           [Country.Portugal, 42],
           [Country.Romania, 26],
           [Country.Latvia, 27],
           [Country.Malta, 28],
           [Country.Azerbaijan, 29],
           [Country.Belgium, 30],
           [Country.Switzerland, 31],
           [Country.Poland, 32],
           [Country.Greece, 33],
           [Country.Armenia, 34],
           [Country.Russia, 35],
           [Country.Belarus, 36],
           [Country.Croatia, 37],
           [Country.Montenegro, 38],
           [Country.San_Marino, 39],
           [Country.Georgia, 40],
           [Country.North_Macedonia, 41],
           [Country.Iceland, 42]]

esc2019 = [[Country.Netherlands, 1],
           [Country.Italy, 2],
           [Country.Russia, 3],
           [Country.Switzerland, 4],
           [Country.Sweden, 5],
           [Country.Norway, 6],
           [Country.North_Macedonia, 7],
           [Country.Azerbaijan, 8],
           [Country.Australia, 9],
           [Country.Iceland, 10],
           [Country.Czech_Republic, 11],
           [Country.Denmark, 12],
           [Country.Cyprus, 13],
           [Country.Malta, 14],
           [Country.Slovenia, 15],
           [Country.France, 16],
           [Country.Albania, 17],
           [Country.Serbia, 18],
           [Country.San_Marino, 19],
           [Country.Estonia, 20],
           [Country.Greece, 21],
           [Country.Spain, 22],
           [Country.Israel, 23],
           [Country.Belarus, 24],
           [Country.Germany, 38],
           [Country.United_Kingdom, 40],
           [Country.Poland, 25],
           [Country.Hungary, 26],
           [Country.Lithuania, 27],
           [Country.Moldova, 28],
           [Country.Belgium, 29],
           [Country.Romania, 30],
           [Country.Georgia, 31],
           [Country.Croatia, 32],
           [Country.Portugal, 33],
           [Country.Latvia, 34],
           [Country.Armenia, 35],
           [Country.Montenegro, 36],
           [Country.Finland, 37],
           [Country.Austria, 38],
           [Country.Ireland, 40]]

esc2020 = []

esc2021 = [[Country.Italy, 1],
           [Country.France, 2],
           [Country.Switzerland, 3],
           [Country.Iceland, 4],
           [Country.Ukraine, 5],
           [Country.Finland, 6],
           [Country.Malta, 7],
           [Country.Lithuania, 8],
           [Country.Russia, 9],
           [Country.Greece, 10],
           [Country.Bulgaria, 11],
           [Country.Portugal, 12],
           [Country.Moldova, 13],
           [Country.Sweden, 14],
           [Country.Serbia, 15],
           [Country.Cyprus, 16],
           [Country.Israel, 17],
           [Country.Norway, 18],
           [Country.Belgium, 19],
           [Country.Azerbaijan, 20],
           [Country.Albania, 21],
           [Country.San_Marino, 22],
           [Country.Netherlands, 32],
           [Country.Spain, 34],
           [Country.Germany, 36],
           [Country.United_Kingdom, 38],
           [Country.Croatia, 23],
           [Country.Romania, 24],
           [Country.Denmark, 25],
           [Country.Austria, 26],
           [Country.Estonia, 27],
           [Country.Slovenia, 28],
           [Country.Poland, 29],
           [Country.Australia, 30],
           [Country.North_Macedonia, 31],
           [Country.Czech_Republic, 32],
           [Country.Ireland, 34],
           [Country.Georgia, 36],
           [Country.Latvia, 38]]

esc2022 = [[Country.Ukraine, 1],
           [Country.United_Kingdom, 2],
           [Country.Spain, 3],
           [Country.Sweden, 4],
           [Country.Serbia, 5],
           [Country.Italy, 6],
           [Country.Moldova, 7],
           [Country.Greece, 8],
           [Country.Portugal, 9],
           [Country.Norway, 10],
           [Country.Netherlands, 11],
           [Country.Poland, 12],
           [Country.Estonia, 13],
           [Country.Lithuania, 14],
           [Country.Australia, 15],
           [Country.Azerbaijan, 16],
           [Country.Switzerland, 17],
           [Country.Romania, 18],
           [Country.Belgium, 19],
           [Country.Armenia, 20],
           [Country.Finland, 21],
           [Country.Czech_Republic, 22],
           [Country.Iceland, 23],
           [Country.France, 37],
           [Country.Germany, 39],
           [Country.Croatia, 24],
           [Country.North_Macedonia, 25],
           [Country.Albania, 26],
           [Country.Cyprus, 27],
           [Country.Israel, 28],
           [Country.Denmark, 29],
           [Country.Latvia, 30],
           [Country.San_Marino, 31],
           [Country.Ireland, 32],
           [Country.Malta, 33],
           [Country.Austria, 34],
           [Country.Montenegro, 35],
           [Country.Bulgaria, 36],
           [Country.Georgia, 37],
           [Country.Slovenia, 39]]

esc = [esc1956, esc1957, esc1958, esc1959, esc1960,
       esc1961, esc1962, esc1963, esc1964, esc1965,
       esc1966, esc1967, esc1968, esc1969, esc1970,
       esc1971, esc1972, esc1973, esc1974, esc1975,
       esc1976, esc1977, esc1978, esc1979, esc1980,
       esc1981, esc1982, esc1983, esc1984, esc1985,
       esc1986, esc1987, esc1988, esc1989, esc1990,
       esc1991, esc1992, esc1993, esc1994, esc1995,
       esc1996, esc1997, esc1998, esc1999, esc2000,
       esc2001, esc2002, esc2003, esc2004, esc2005,
       esc2006, esc2007, esc2007, esc2009, esc2010,
       esc2011, esc2012, esc2013, esc2014, esc2015,
       esc2016, esc2017, esc2018, esc2019, esc2020,
       esc2021, esc2022]